### ISSUE TITLE
Setting change_list=False automatically removes button from changeform

### ISSUE THREAD

**Issue by Tauassar** [saxix/django-admin-extra-buttons#11]
Setting change_list=False removes button from admin change form even if change_form=True property is set.

**Comment by alilotfi** [comment]
The problem is that the library tries to automatically detect whether it should show the button in the Change List/Change Form or not and it fails to detect yours in suitable to be shown in the Change Form.
It's most likely because your function does not have any other arguments than `self` and `request`. Try adding a `pk` argument to your button function.

**Comment by Tauassar** [comment]
> The problem is that the library tries to automatically detect whether it should show the button in the Change List/Change Form or not and it fails to detect yours in suitable to be shown in the Change Form. It's most likely because your function does not have any other arguments than `self` and `request`. Try adding a `pk` argument to your button function.

Thank you, adding pk to a function indeed helped to fix this issue
